config/routes.rb
Rails.application.routes.draw do
  resources :offers
  devise_for :users
  root 'home#index'

  get 'home/about'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :offers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = current_user.offers.build
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = current_user.offers.build(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:title, :description, :price, :email_address, :phone)
    end
    
    def correct_user
      @offer = current_user.offers.find_by(id: params[:id])
      redirect_to offers_path, notice: "You are not authorized to edit this offer" if @offer.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">RC</a>
  <div>

<ul class="nav navbar-nav navbar-right">
<li><%= link_to 'Rent my car', root_path %></li>
<li><%= link_to 'About', home_about_path %></li>
<li><%= link_to 'Listing Offers', offers_path %></li>

     <% if user_signed_in? %>
          <li><%= link_to 'Edit', edit_user_registration_path, class: 'navbar-link' %></li>
          <li><%= link_to 'New offer', new_offer_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'navbar-link' %></li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path, class: 'navbar-link' %></li>
          <li><%= link_to 'Registration', new_user_registration_path, class: 'navbar-link' %></li>
        <% end %>
    
</ul>
</div>
</nav>

app/views/home/about.html.erb
<h1>ABOUT...</h1>
<p1>This is a platform with cars offers. This is for people who want rent their car another people for a day, a month</p1>

app/views/home/index.html.erb
<div class="jumbotron">
    <h1>RENT MY CAR</h1>
    <%= link_to 'About us', home_about_path, class: 'btn btn-success' %>
    <%= link_to 'Rent my car', root_path, class: 'btn btn-success btn-lg' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'home/header' %>

<div class="container">
    <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
    
  <%= yield %>
</div>

</body>
</html>

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Offers</h1>

  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Email address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.title %></td>
        <td><%= offer.description %></td>
        <td><%= offer.price %></td>
        <td><%= offer.email_address %></td>
        <td><%= offer.phone %></td>
        <td><%= link_to 'Show', offer %></td>
        <% if offer.user == current_user %>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offer.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offer.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @offer.price %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @offer.email_address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @offer.phone %>
</p>
<% if @offer.user == current_user %>
<%= link_to 'Edit', edit_offer_path(@offer) %> 
<% end %>
<%= link_to 'Back', offers_path %>